package main

const (
	SEMTOK_CLASS       = "class"
	SEMTOK_KEYWORD     = "keyword"
	SEMTOK_PROPERTY    = "property"
	SEMTOK_STRING      = "string"
	SEMTOK_ENUM_MEMBER = "enumMember"
)

const (
	SEMTOK_CLASS_INDEX = iota
	SEMTOK_KEYWORD_INDEX
	SEMTOK_PROPERTY_INDEX
	SEMTOK_STRING_INDEX
	SEMTOK_ENUM_MEMBER_INDEX
)
